FROM python:3.12-slim


# Prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1


# Display logs immediately
ENV PYTHONUNBUFFERED=1


# Set Working Directory
WORKDIR /app


# Install Linux packages
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


# Copy requirements first (Docker cache optimization)
COPY requirements.txt .


# Install Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Expose Django Port
EXPOSE 8000

# Start Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]





#============== command=============

# docker build -f devops/dockerfile -t django-app . # build image
# docker run -d -p 8000:8000 django-app # run image in dettached mode 
# docker run -p 8000:8000 django-app # run image in foreground mode
# docker stop <container_id> # stop image 
# docker rm <container_id> # remove image
# docker ps # list all images
# docker ps -a # list all images including stopped ones
# docker ps -q # list all images in quiet mode
# docker ps -a -q # list all images including stopped ones in quiet mode
